### ISSUE TITLE
[BUG] Disabling volume warning and pulse eq

### ISSUE THREAD

**Issue by Bonsoir98** [DHD2280/Oxygen-Customizer#52] opened 2024-09-05 14:26 UTC
### Describe the bug

Hi, as in the title both of this features doesn't work on my OnePlus Nord 4. Everything else works pefectly. 
PS.: Love the app, and the work you put in. 

### Expected behavior

Media volume on bluetooth headphones without warning. The visualizer displaying. 

### Device information

- Device: OnePlus Nord 4
- OS: Oxygen OS 14.1
- App version: beta-10

**Comment by DHD2280** [comment] 2024-09-05 14:44
Thank you 😊 

Volume warning fixed in the latest nightly (check commits).
For pulse, do you have spatial audio or everything else enabled?
You can download nightlies by checking GitHub actions.

**Comment by Bonsoir98** [comment] 2024-09-05 15:55
Installed the nightly version, and in fact the volume warning works like a charm. It seems to have fixed pulse as well, tried to switch on and off V4A as well, I can see the visualizer on aod and lock screen but it seems to have a minor bug by breaking the playback of songs if double tapping the screen/pressing power button the volume goes down for half a second to come back to normal. Aparat from that everything is a masterpiece 😁

**Comment by DHD2280** [comment] 2024-09-05 16:24
I think that this issue isn't related to OC.
You can check if the issue is related by disabling OC in lsposed and reboot.
If you have that issue of playback, send logs here.

**Comment by Bonsoir98** [comment] 2024-09-05 18:59
I mean this happens only with pulse turned on. If it's turned off all is fine.

**Closed as completed** 2024-09-06 17:06 UTC
Labels: bug
